export type WealthCategory =
  | "SOVEREIGN"
  | "MONARCHY"
  | "FAMILY"
  | "INDIVIDUAL";

export interface WealthEntitySeed {
  category: WealthCategory;
  country: string;
  region?: string;
  name: string;
  vehicleName?: string;
  /** AUM range in USD billions */
  aumMinUsd: number;
  aumMaxUsd: number;
  /** Fraction of total AUM disclosed to admin (e.g. 0.08 = 8%) */
  displayFraction: number;
  mandate: string;
  sortOrder: number;
}

export const sovereignWealthFunds: WealthEntitySeed[] = [
  {
    category: "SOVEREIGN",
    country: "Norway",
    region: "Europe",
    name: "Government Pension Fund Global",
    vehicleName: "GPFG",
    aumMinUsd: 2000,
    aumMaxUsd: 2500,
    displayFraction: 0.06,
    mandate:
      "Excess North Sea oil revenues; builds intergenerational wealth via global public equities.",
    sortOrder: 1,
  },
  {
    category: "SOVEREIGN",
    country: "China",
    region: "Asia Pacific",
    name: "China Investment Corporation",
    vehicleName: "CIC",
    aumMinUsd: 1300,
    aumMaxUsd: 1570,
    displayFraction: 0.05,
    mandate:
      "Foreign exchange reserves; focused on diversifying China's massive state holdings.",
    sortOrder: 2,
  },
  {
    category: "SOVEREIGN",
    country: "China",
    region: "Asia Pacific",
    name: "SAFE Investment Company",
    vehicleName: "SAFE IC",
    aumMinUsd: 1690,
    aumMaxUsd: 1980,
    displayFraction: 0.04,
    mandate:
      "Managed by the State Administration of Foreign Exchange; active global fixed-income and equity player.",
    sortOrder: 3,
  },
  {
    category: "SOVEREIGN",
    country: "United Arab Emirates",
    region: "Middle East",
    name: "Abu Dhabi Investment Authority",
    vehicleName: "ADIA",
    aumMinUsd: 1100,
    aumMaxUsd: 1200,
    displayFraction: 0.07,
    mandate:
      "Multi-decade oil export surpluses; invests globally across dozens of asset classes.",
    sortOrder: 4,
  },
  {
    category: "SOVEREIGN",
    country: "Kuwait",
    region: "Middle East",
    name: "Kuwait Investment Authority",
    vehicleName: "KIA",
    aumMinUsd: 930,
    aumMaxUsd: 1070,
    displayFraction: 0.08,
    mandate:
      "World's oldest SWF (est. 1953); operates the Future Generations Fund to safeguard oil windfalls.",
    sortOrder: 5,
  },
  {
    category: "SOVEREIGN",
    country: "Singapore",
    region: "Asia Pacific",
    name: "GIC Private Limited",
    vehicleName: "GIC",
    aumMinUsd: 850,
    aumMaxUsd: 1000,
    displayFraction: 0.06,
    mandate:
      "Government fiscal reserves; manages Singapore's foreign exchange assets with a long-term global horizon.",
    sortOrder: 6,
  },
  {
    category: "SOVEREIGN",
    country: "Indonesia",
    region: "Asia Pacific",
    name: "BPI Danantara",
    vehicleName: "Danantara",
    aumMinUsd: 900,
    aumMaxUsd: 1000,
    displayFraction: 0.05,
    mandate:
      "Consolidated super-fund managing state-owned entities to drive structural expansion.",
    sortOrder: 7,
  },
  {
    category: "SOVEREIGN",
    country: "Saudi Arabia",
    region: "Middle East",
    name: "Public Investment Fund",
    vehicleName: "PIF",
    aumMinUsd: 900,
    aumMaxUsd: 1100,
    displayFraction: 0.07,
    mandate:
      "Saudi Vision 2030 sovereign vehicle; global equities, infrastructure, tech, and giga-projects.",
    sortOrder: 8,
  },
  {
    category: "SOVEREIGN",
    country: "Qatar",
    region: "Middle East",
    name: "Qatar Investment Authority",
    vehicleName: "QIA",
    aumMinUsd: 530,
    aumMaxUsd: 600,
    displayFraction: 0.09,
    mandate:
      "Liquefied natural gas (LNG) profits; pursues global infrastructure, real estate, and sports assets.",
    sortOrder: 9,
  },
  {
    category: "SOVEREIGN",
    country: "Singapore",
    region: "Asia Pacific",
    name: "Temasek Holdings",
    vehicleName: "Temasek",
    aumMinUsd: 320,
    aumMaxUsd: 340,
    displayFraction: 0.1,
    mandate:
      "Commercial state-owned wealth; active equity investor weighted toward tech and life sciences.",
    sortOrder: 10,
  },
  {
    category: "SOVEREIGN",
    country: "Australia",
    region: "Oceania",
    name: "Future Fund",
    vehicleName: "Future Fund",
    aumMinUsd: 210,
    aumMaxUsd: 255,
    displayFraction: 0.12,
    mandate:
      "Non-commodity fiscal surpluses; exposed to unlisted private equity, real assets, and alternatives.",
    sortOrder: 11,
  },
  {
    category: "SOVEREIGN",
    country: "Bahrain",
    region: "Middle East",
    name: "Mumtalakat Holding Company",
    vehicleName: "Mumtalakat",
    aumMinUsd: 18,
    aumMaxUsd: 22,
    displayFraction: 0.15,
    mandate: "Kingdom of Bahrain sovereign wealth; diversified domestic and international holdings.",
    sortOrder: 12,
  },
  {
    category: "SOVEREIGN",
    country: "Oman",
    region: "Middle East",
    name: "Oman Investment Authority",
    vehicleName: "OIA",
    aumMinUsd: 40,
    aumMaxUsd: 50,
    displayFraction: 0.11,
    mandate: "Merged State General Reserve Fund and Oman Investment Fund; oil transition diversification.",
    sortOrder: 13,
  },
  {
    category: "SOVEREIGN",
    country: "Morocco",
    region: "Africa",
    name: "Ithmar Capital",
    vehicleName: "CDG / Ithmar",
    aumMinUsd: 45,
    aumMaxUsd: 55,
    displayFraction: 0.1,
    mandate: "Caisse de Dépôt et de Gestion strategic fund; infrastructure and African growth markets.",
    sortOrder: 14,
  },
];

export const privateWealthEntities: WealthEntitySeed[] = [
  {
    category: "FAMILY",
    country: "United States",
    region: "Americas",
    name: "The Walton Family",
    vehicleName: "Walton Enterprises LLC",
    aumMinUsd: 225,
    aumMaxUsd: 250,
    displayFraction: 0.08,
    mandate: "Inherited Walmart retail fortune (Rob, Jim, and Alice Walton).",
    sortOrder: 1,
  },
  {
    category: "INDIVIDUAL",
    country: "United States",
    region: "Americas",
    name: "Bill Gates",
    vehicleName: "Cascade Investment",
    aumMinUsd: 170,
    aumMaxUsd: 185,
    displayFraction: 0.07,
    mandate: "Microsoft co-founder; diversifies into real estate, energy, and hospitality.",
    sortOrder: 2,
  },
  {
    category: "MONARCHY",
    country: "United Arab Emirates",
    region: "Middle East",
    name: "Al Maktoum Family",
    vehicleName: "Dubai Holding",
    aumMinUsd: 135,
    aumMaxUsd: 145,
    displayFraction: 0.06,
    mandate: "Private global investment conglomerate of Dubai's ruling family.",
    sortOrder: 3,
  },
  {
    category: "MONARCHY",
    country: "Saudi Arabia",
    region: "Middle East",
    name: "House of Saud",
    vehicleName: "Royal Family Office",
    aumMinUsd: 120,
    aumMaxUsd: 160,
    displayFraction: 0.04,
    mandate: "Ruling monarchy private holdings; energy, real estate, and global institutional stakes.",
    sortOrder: 4,
  },
  {
    category: "MONARCHY",
    country: "Brunei",
    region: "Asia Pacific",
    name: "Sultan Hassanal Bolkiah",
    vehicleName: "Brunei Investment Agency",
    aumMinUsd: 30,
    aumMaxUsd: 40,
    displayFraction: 0.05,
    mandate: "Sovereign monarchy reserves; global blue-chip portfolio managed with absolute discretion.",
    sortOrder: 5,
  },
  {
    category: "INDIVIDUAL",
    country: "Spain",
    region: "Europe",
    name: "Amancio Ortega",
    vehicleName: "Pontegadea Inversiones",
    aumMinUsd: 115,
    aumMaxUsd: 125,
    displayFraction: 0.09,
    mandate: "Zara founder; reinvests fashion dividends into prime global real estate.",
    sortOrder: 6,
  },
  {
    category: "INDIVIDUAL",
    country: "United States",
    region: "Americas",
    name: "Jeff Bezos",
    vehicleName: "Bezos Expeditions",
    aumMinUsd: 105,
    aumMaxUsd: 115,
    displayFraction: 0.08,
    mandate: "Amazon founder; aerospace (Blue Origin), media, and early-stage technology.",
    sortOrder: 7,
  },
  {
    category: "MONARCHY",
    country: "Qatar",
    region: "Middle East",
    name: "Al Thani Royal Family",
    vehicleName: "Qatar Royal Portfolio",
    aumMinUsd: 90,
    aumMaxUsd: 110,
    displayFraction: 0.05,
    mandate: "Ruling emirs' private office; luxury real estate, sports, and European holdings.",
    sortOrder: 8,
  },
  {
    category: "MONARCHY",
    country: "Kuwait",
    region: "Middle East",
    name: "Al Sabah Royal Family",
    vehicleName: "Kuwait Royal Holdings",
    aumMinUsd: 80,
    aumMaxUsd: 100,
    displayFraction: 0.06,
    mandate: "Ruling family private wealth; energy-linked assets and international custody mandates.",
    sortOrder: 9,
  },
  {
    category: "INDIVIDUAL",
    country: "Saudi Arabia",
    region: "Middle East",
    name: "Prince Alwaleed bin Talal",
    vehicleName: "Kingdom Holding Company",
    aumMinUsd: 18,
    aumMaxUsd: 22,
    displayFraction: 0.12,
    mandate: "High-profile royal investor; hotels, banking, and global equity positions.",
    sortOrder: 10,
  },
  {
    category: "MONARCHY",
    country: "Thailand",
    region: "Asia Pacific",
    name: "Crown Property Bureau",
    vehicleName: "CPB",
    aumMinUsd: 40,
    aumMaxUsd: 50,
    displayFraction: 0.04,
    mandate: "Constitutional monarchy property bureau; vast domestic land and corporate interests.",
    sortOrder: 11,
  },
  {
    category: "MONARCHY",
    country: "Monaco",
    region: "Europe",
    name: "House of Grimaldi",
    vehicleName: "Compagnie Monégasque de Banque",
    aumMinUsd: 2,
    aumMaxUsd: 4,
    displayFraction: 0.15,
    mandate: "Principality ruling family; banking, real estate, and hospitality across the Riviera.",
    sortOrder: 12,
  },
  {
    category: "MONARCHY",
    country: "Liechtenstein",
    region: "Europe",
    name: "Princely Family of Liechtenstein",
    vehicleName: "LGT Group",
    aumMinUsd: 5,
    aumMaxUsd: 8,
    displayFraction: 0.1,
    mandate: "Sovereign princely house; private banking and multi-generational family office.",
    sortOrder: 13,
  },
  {
    category: "MONARCHY",
    country: "Jordan",
    region: "Middle East",
    name: "Hashemite Royal Court",
    vehicleName: "King Abdullah II Fund",
    aumMinUsd: 1,
    aumMaxUsd: 2,
    displayFraction: 0.14,
    mandate: "Royal family investment arm; regional stability-focused diversified holdings.",
    sortOrder: 14,
  },
  {
    category: "FAMILY",
    country: "Denmark",
    region: "Europe",
    name: "The Kristiansen Family",
    vehicleName: "KIRKBI",
    aumMinUsd: 30,
    aumMaxUsd: 35,
    displayFraction: 0.11,
    mandate: "Generational holding company for the owners of the LEGO brand.",
    sortOrder: 15,
  },
  {
    category: "MONARCHY",
    country: "United Kingdom",
    region: "Europe",
    name: "The British Royal Family",
    vehicleName: "Duchy of Lancaster",
    aumMinUsd: 0.8,
    aumMaxUsd: 1.2,
    displayFraction: 0.12,
    mandate: "Privy purse and duchy estates; agricultural land and urban commercial property.",
    sortOrder: 16,
  },
];

export const allWealthEntities: WealthEntitySeed[] = [
  ...sovereignWealthFunds,
  ...privateWealthEntities,
];
